### ISSUE TITLE
[Feature Request] 更低的Python版本支持

### ISSUE THREAD

**Issue by Lawrenceeeeeeee** [I-love-study/py-rotaeno-stablizer-gui#2]
### Bug 描述

3.11以下的python不支持

### 复现步骤

旧版本python启动本项目的时候就遇到这个问题

### 期望行为

建议注明适配的python版本

### 截图 / 相关视频

Traceback (most recent call last):
  File "/Users/lawrence/anaconda3/envs/python_rotaeno_stablizer/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/lawrence/anaconda3/envs/python_rotaeno_stablizer/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/lawrence/Downloads/py-rotaeno-stablizer-gui-main/rotaeno_stablizer/__main__.py", line 3, in <module>
    import tomllib
ModuleNotFoundError: No module named 'tomllib'

### 稳定器版本

0.1.0

### 游玩设备

iPhone 14

**Comment by I-love-study** [comment]
事实上在pyproject.toml中确实写到依赖python版本为3.11及以上（readme忘记写了，后面会补上）
因为考虑到3.11相比3.10性能提升不小，可能会提升视频编码速度。
不过到时候可以去测试一下到底能提高多少
如果都差不多，就向下支持一下。

**Comment by I-love-study** [comment]
已向下支持到 Python 3.10，然后考虑到 Python 3.9 将于 2025.8.30 进入 EOL，所以不考虑相关支持了。
~~没想到是通过鸽了一年实现向下兼容（~~
如有充足理由后再考虑重新 Open
