### ISSUE TITLE
[ Bug ] 输出视频存在轻微的抖动

### ISSUE THREAD

**Issue by Lawrenceeeeeeee** [I-love-study/py-rotaeno-stablizer-gui#3]
### Bug 描述

输出的视频在大幅度旋转的地方存在肉眼可见的抖动

### 复现步骤

正常的稳定流程

### 期望行为

是否能通过调参的方法修正？还是说这个是ffmpeg无法避免的问题？

### 稳定器版本

不清楚这是哪个版本，2024-7-14 clone下来的

### 游玩设备

iPhone 14

**Comment by I-love-study** [comment]
是否有示例视频以便判断详情
因为当前main分支还不是通过ffmpeg直接旋转的
所以应该是平滑出现了问题
可以增加 `--window-size 1` 来看看能不能解决
顺带一提，是否能够发送一份示例视频

**Comment by Lawrenceeeeeeee** [comment]
视频太大，没发直接传到github
我先贴一个百度网盘链接在这儿
链接: https://pan.baidu.com/s/1ZqTtPdUfNlmvEsQJgX-x7w?pwd=wmdi 提取码: wmdi 复制这段内容后打开百度网盘手机App，操作更方便哦 
--来自百度网盘超级会员v5的分享

**Comment by Lawrenceeeeeeee** [comment]
> 是否有示例视频以便判断详情 因为当前main分支还不是通过ffmpeg直接旋转的 所以应该是平滑出现了问题 可以增加 `--window-size 1` 来看看能不能解决 顺带一提，是否能够发送一份示例视频

您提到的这个方法好像没有解决问题，而且还报错了

```
PY Rotaeno Stablizer: https://github.com/I-love-study/py-rotaeno-stablizer-gui

请输入原始文件: D:\Users\Administrator\Desktop\My_Projects\baseline.mp4
输出文件： D:\Users\Administrator\Desktop\My_Projects\baseline_out.mp4
请选择直播模式版本 [1/2] (2):
是否自动裁切成16:9 ([y]/n) : n
是否使用圆形切环 ([y]/n) : y
是否输出正方形版本 ([y]/n) : y
是否自动裁切成16:9 (y/[n]) : n
是否需要背景图片 ([y]/n) : n
请输入平滑参数： (3):
请输入输出视频高度（0 为系统自动选择） (0): 1
请选择输出视频编码器 (hevc_nvenc):
请选择输出视频比特率 (8m):
✅[1/3]Loading Video... Complete
D:\Users\Administrator\Desktop\My_Projects\py-rotaeno-stablizer-gui\rotaeno_stablizer\rotation_calc.py:25:
RuntimeWarning: Mean of empty slice.
  bottom_left = frame[-self.O:-self.O + self.S, self.O:self.O + self.S].mean(axis=(0, 1))
D:\Users\Administrator\anaconda3\Lib\site-packages\numpy\_core\_methods.py:130: RuntimeWarning: invalid value
encountered in divide
  ret = um.true_divide(
D:\Users\Administrator\Desktop\My_Projects\py-rotaeno-stablizer-gui\rotaeno_stablizer\rotation_calc.py:26:
RuntimeWarning: Mean of empty slice.
  top_left = frame[self.O:self.O + self.S, self.O:self.O + self.S].mean(axis=(0, 1))
D:\Users\Administrator\Desktop\My_Projects\py-rotaeno-stablizer-gui\rotaeno_stablizer\rotation_calc.py:27:
RuntimeWarning: Mean of empty slice.
  bottom_right = frame[-self.O:-self.O + self.S, -self.O:-self.O + self.S].mean(axis=(0, 1))
D:\Users\Administrator\Desktop\My_Projects\py-rotaeno-stablizer-gui\rotaeno_stablizer\rotation_calc.py:28:
RuntimeWarning: Mean of empty slice.
  top_right = frame[self.O:self.O + self.S, -self.O:-self.O + self.S].mean(axis=(0, 1))
Traceback (most recent call last):
  File "D:\Users\Administrator\Desktop\My_Projects\py-rotaeno-stablizer-gui\rotaeno_stablizer\ffmpeg.py", line 287, in
start_process
    self.pipe.stdin.write(frame)
OSError: [Errno 22] Invalid argument

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Users\Administrator\Desktop\My_Projects\py-rotaeno-stablizer-gui\rotaeno_stablizer\ffmpeg.py", line 292, in
start_process
    raise FFMpegError("\n".join(line)) from e
rotaeno_stablizer.ffmpeg.FFMpegError: [hevc_nvenc @ 000001bbe916a780] InitializeEncoder failed: invalid param (8):
Frame dimensions are less than the minimum supported value.
[vost#0:0/hevc_nvenc @ 000001bbe916a2c0] Error while opening encoder - maybe incorrect parameters such as bit_rate,
rate, width or height.
[fc#0 @ 000001bbe9167a40] Error sending frames to consumers: Invalid argument
[fc#0 @ 000001bbe9167a40] Task finished with error code: -22 (Invalid argument)
[fc#0 @ 000001bbe9167a40] Terminating thread with return code -22 (Invalid argument)
[vost#0:0/hevc_nvenc @ 000001bbe916a2c0] Could not open encoder before EOF
[vost#0:0/hevc_nvenc @ 000001bbe916a2c0] Task finished with error code: -22 (Invalid argument)
[vost#0:0/hevc_nvenc @ 000001bbe916a2c0] Terminating thread with return code -22 (Invalid argument)
[out#0/mp4 @ 000001bbe9196480] Nothing was written into output file, because at least one of its streams received no
packets.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\Administrator\anaconda3\Lib\threading.py", line 1052, in _bootstrap_inner
    self.run()
  File "D:\Users\Administrator\anaconda3\Lib\threading.py", line 989, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Users\Administrator\Desktop\My_Projects\py-rotaeno-stablizer-gui\rotaeno_stablizer\ffmpeg.py", line 279, in
start_process
    with self.pipe:
  File "D:\Users\Administrator\anaconda3\Lib\subprocess.py", line 1099, in __exit__
    self.stdin.close()
OSError: [Errno 22] Invalid argument
⏳[2/3]Rendering Video  ---------------------------------------   2% 0:00:01 0:00:25 FPS: 386
```

**Comment by I-love-study** [comment]
> > 是否有示例视频以便判断详情 因为当前main分支还不是通过ffmpeg直接旋转的 所以应该是平滑出现了问题 可以增加 `--window-size 1` 来看看能不能解决 顺带一提，是否能够发送一份示例视频
> 
> 您提到的这个方法好像没有解决问题，而且还报错了
> 
> ```
> PY Rotaeno Stablizer: https://github.com/I-love-study/py-rotaeno-stablizer-gui
> 
> 请输入原始文件: D:\Users\Administrator\Desktop\My_Projects\baseline.mp4
> 输出文件： D:\Users\Administrator\Desktop\My_Projects\baseline_out.mp4
> 请选择直播模式版本 [1/2] (2):
> 是否自动裁切成16:9 ([y]/n) : n
> 是否使用圆形切环 ([y]/n) : y
> 是否输出正方形版本 ([y]/n) : y
> 是否自动裁切成16:9 (y/[n]) : n
> 是否需要背景图片 ([y]/n) : n
> 请输入平滑参数： (3):
> 请输入输出视频高度（0 为系统自动选择） (0): 1
> 请选择输出视频编码器 (hevc_nvenc):
> 请选择输出视频比特率 (8m):
> ✅[1/3]Loading Video... Complete
> D:\Users\Administrator\Desktop\My_Projects\py-rotaeno-stablizer-gui\rotaeno_stablizer\rotation_calc.py:25:
> RuntimeWarning: Mean of empty slice.
>   bottom_left = frame[-self.O:-self.O + self.S, self.O:self.O + self.S].mean(axis=(0, 1))
> D:\Users\Administrator\anaconda3\Lib\site-packages\numpy\_core\_methods.py:130: RuntimeWarning: invalid value
> encountered in divide
>   ret = um.true_divide(
> D:\Users\Administrator\Desktop\My_Projects\py-rotaeno-stablizer-gui\rotaeno_stablizer\rotation_calc.py:26:
> RuntimeWarning: Mean of empty slice.
>   top_left = frame[self.O:self.O + self.S, self.O:self.O + self.S].mean(axis=(0, 1))
> D:\Users\Administrator\Desktop\My_Projects\py-rotaeno-stablizer-gui\rotaeno_stablizer\rotation_calc.py:27:
> RuntimeWarning: Mean of empty slice.
>   bottom_right = frame[-self.O:-self.O + self.S, -self.O:-self.O + self.S].mean(axis=(0, 1))
> D:\Users\Administrator\Desktop\My_Projects\py-rotaeno-stablizer-gui\rotaeno_stablizer\rotation_calc.py:28:
> RuntimeWarning: Mean of empty slice.
>   top_right = frame[self.O:self.O + self.S, -self.O:-self.O + self.S].mean(axis=(0, 1))
> Traceback (most recent call last):
>   File "D:\Users\Administrator\Desktop\My_Projects\py-rotaeno-stablizer-gui\rotaeno_stablizer\ffmpeg.py", line 287, in
> start_process
>     self.pipe.stdin.write(frame)
> OSError: [Errno 22] Invalid argument
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "D:\Users\Administrator\Desktop\My_Projects\py-rotaeno-stablizer-gui\rotaeno_stablizer\ffmpeg.py", line 292, in
> start_process
>     raise FFMpegError("\n".join(line)) from e
> rotaeno_stablizer.ffmpeg.FFMpegError: [hevc_nvenc @ 000001bbe916a780] InitializeEncoder failed: invalid param (8):
> Frame dimensions are less than the minimum supported value.
> [vost#0:0/hevc_nvenc @ 000001bbe916a2c0] Error while opening encoder - maybe incorrect parameters such as bit_rate,
> rate, width or height.
> [fc#0 @ 000001bbe9167a40] Error sending frames to consumers: Invalid argument
> [fc#0 @ 000001bbe9167a40] Task finished with error code: -22 (Invalid argument)
> [fc#0 @ 000001bbe9167a40] Terminating thread with return code -22 (Invalid argument)
> [vost#0:0/hevc_nvenc @ 000001bbe916a2c0] Could not open encoder before EOF
> [vost#0:0/hevc_nvenc @ 000001bbe916a2c0] Task finished with error code: -22 (Invalid argument)
> [vost#0:0/hevc_nvenc @ 000001bbe916a2c0] Terminating thread with return code -22 (Invalid argument)
> [out#0/mp4 @ 000001bbe9196480] Nothing was written into output file, because at least one of its streams received no
> packets.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:\Users\Administrator\anaconda3\Lib\threading.py", line 1052, in _bootstrap_inner
>     self.run()
>   File "D:\Users\Administrator\anaconda3\Lib\threading.py", line 989, in run
>     self._target(*self._args, **self._kwargs)
>   File "D:\Users\Administrator\Desktop\My_Projects\py-rotaeno-stablizer-gui\rotaeno_stablizer\ffmpeg.py", line 279, in
> start_process
>     with self.pipe:
>   File "D:\Users\Administrator\anaconda3\Lib\subprocess.py", line 1099, in __exit__
>     self.stdin.close()
> OSError: [Errno 22] Invalid argument
> ⏳[2/3]Rendering Video  ---------------------------------------   2% 0:00:01 0:00:25 FPS: 386
> ```

```
请输入平滑参数： (3):
请输入输出视频高度（0 为系统自动选择） (0): 1
```

是平滑参数，不是视频高度😂

**Comment by Lawrenceeeeeeee** [comment]
> 
> 是平滑参数，不是视频高度😂

抱歉，眼瞎了（）

但是还是有问题

```
请输入平滑参数： (3): 1
请输入输出视频高度（0 为系统自动选择） (0):
请选择输出视频编码器 (hevc_nvenc):
请选择输出视频比特率 (8m):
✅[1/3]Loading Video... Complete
⏳[2/3]Rendering Video ----------------------------------------   0% 0:00:00 -:--:-- FPS: ?
Traceback (most recent call last):
  File "D:\Users\Administrator\anaconda3\Lib\threading.py", line 1052, in _bootstrap_inner
    self.run()
  File "D:\Users\Administrator\anaconda3\Lib\threading.py", line 989, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Users\Administrator\Desktop\My_Projects\py-rotaeno-stablizer-gui\rotaeno_stablizer\__init__.py", line 297, in process_video_cli
    self.process_video(input_reader, output_writer, lambda: progress.advance(task))
  File "D:\Users\Administrator\Desktop\My_Projects\py-rotaeno-stablizer-gui\rotaeno_stablizer\__init__.py", line 263, in process_video
    self.rotation_method.wake_up(wakeup_elems)
  File "D:\Users\Administrator\Desktop\My_Projects\py-rotaeno-stablizer-gui\rotaeno_stablizer\rotation_calc.py", line 80, in wake_up
    angle = self.method(*self.get_points(frames[0][:,:,:3]))
                                         ~~~~~~^^^
IndexError: list index out of range
```

**Comment by I-love-study** [comment]
> 但是还是有问题

尴尬了，没有给`window_size=1`专门做适配
试试将`rotation_calc.py`改一下
（因为没有测试环境，所以请帮忙测试以下看看是否可行）

```python
if len(frames) != self.wake_up_num:
    raise ValueError("Wrong angle count")
if len(frames) == 0:
    return
```

**Comment by Lawrenceeeeeeee** [comment]
> > 但是还是有问题
> 
> 尴尬了，没有给`window_size=1`专门做适配 试试将`rotation_calc.py`改一下（约80行） （因为没有测试环境，所以请帮忙测试以下看看是否可行）
> 
> ```python
> if len(frames) != self.wake_up_num:
>     raise ValueError("Wrong angle count")
> if len(frames) == 0:
>     return
> ```

其实还是有问题（
不过我帮您改了，等会儿我发个PR

**Comment by Lawrenceeeeeeee** [comment]
而且我这边其实还有个问题，我的ffmpeg是支持cuda的，但是实际运行起来似乎没有充分利用GPU，我也选上hevc_nvenc了，不知道我这边是不是个例

**Comment by I-love-study** [comment]
> 而且我这边其实还有个问题，我的ffmpeg是支持cuda的，但是实际运行起来似乎没有充分利用GPU，我也选上hevc_nvenc了，不知道我这边是不是个例

有两种可能性
1. 达到了pipe的传输上限，这个问题除降低分辨率外，以现有方案无解，好的解决方案就是不经过python，直接让ffmpeg处理https://github.com/I-love-study/py-rotaeno-stablizer-gui/issues/1#issuecomment-2173602657
2. CPU吃满，因为现在旋转这一步还是在opencv-python中处理，且ffmpeg的overlay也是吃CPU的。可能会导致CPU吃满了，显卡还没吃满。解决方法可能是将overlay filter改成overlay_cuda（未经验证）

**Comment by Lawrenceeeeeeee** [comment]
> 2\. CPU吃满，因为现在旋转这一步还是在opencv-python中处理，且ffmpeg的overlay也是吃CPU的。可能会导致CPU吃满了，显卡还没吃满。解决方法可能是将overlay filter改成overlay_cuda（未经验证）

这个在哪儿改

**Comment by I-love-study** [comment]
> 这个在哪儿改

https://github.com/I-love-study/py-rotaeno-stablizer-gui/blob/1954a1d758b7f0fb32cf1192ae31aa2b0edcef34/rotaeno_stablizer/ffmpeg.py#L255

不过只是简单把overlay改成overlay_cuda可能不起作用，可能还要添加hwupload_cuda，scale_npp等滤镜
相关问题可以看看这里
https://forums.developer.nvidia.com/t/how-to-use-ffmpeg-overlay-cuda-filter-to-create-sbs-video/147495/2

**Comment by Lawrenceeeeeeee** [comment]
您那边测试的时候的渲染速度如何
我这边测试的时候是 渲染时长/原视频时长 = 1.06

**Comment by I-love-study** [comment]
> 您那边测试的时候的渲染速度如何 我这边测试的时候是 渲染时长/原视频时长 = 1.06

是带上overlay_cuda，没测试过？
不过不带上的话渲染速度基本相同
顺带一提，我在纯ffmpeg转换的话在1080p下可以达到不到1（具体记不得了，大概0.9x）

**Comment by Lawrenceeeeeeee** [comment]
还有，我感觉其实这个平滑效果的实际观感并不是很好，会有种眩晕感，反而不如不平滑。或者可以用其他的平滑方式？比如从旋转角序列的二阶差分来看看有没有异常值，只对异常值做差值之类的？

**Comment by Lawrenceeeeeeee** [comment]
其实官方的这个v2已经够平稳的了，当初平滑效果是为了v1设计的吧

**Comment by I-love-study** [comment]
已发布正式 1.0.0 版本，并删除了关于视频平滑的代码。
如还有问题，请另开 issue
